language: node_js
dist: trusty
node_js: stable
sudo: required
addons:
  chrome: stable
install: true
before_install:
- npm install
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
branches:
  only: master
cache:
  directories: node_modules
script:
- npm run test
- npm run buildProd
before_deploy:
- npm install -g tslint
- npm install -g typescript
- cd functions && npm install
- cd ..
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "fTO3lwNGl//6+yTFVKwX+uImh2FgxI6oc6KtWcQjW2odzQnElqr5BAYepYoUd3WGHTKNhD1rUimdUsejDFzlAfhWVOSUgHMt0m2Reb48nHyKfeGVqSj0IoWqGXU5hf1WXHbkgkyBuFxNW/KY7FcdlBHPrAVD1mMhi1SV8nDfMpcjgs54hQBNClmOtrNa02d2260Un8NBvdWMFCoqe2TsWwPdjI6lkQroTNacXjy90F51U+6B1Zon5IW9PL6z+rpMlcgiQD87JO0+eGGGoik5EWEjENnUp8/I2oSu/BUofvnZZg2x0KCg6AqyTVtckcKdS7qiYblZmFVpw/cjHL3JfsCGwvwijclQt9p+nithqq+OvKDvmn5ARa9G7oir0bUuxhj2Ud+sd5ELrwfVTnpOZcSGEJbHfgWhbf93i2bTbW6zydyYga+feTXvic5CIVJvxjIk3WI99kHC2gBwTIbgm4etLFl/xSOuWich5bipYFacQgoDGQ0IFJpob3nlAN+Vny06K+iwWmohShqVnyE40Zrlfu1+TkT9/+fkQkZy8SobeFb1Ligk3fDgxJZKAaT/C1zd3MF8gwfOfou65h6NqaPIQk0BZTz+r72fIfrMBCIwnzw5jTD6TWx0obVzbxvCtIy4EwLB54E0HFiR91ft8rg06eOLq4TgV24cN55ms3g="
